### PR TITLE
Updated packetgen.lua after re-merging from base MoonGen repo

### PR DESCRIPTION
**Pull request by NetronomeMoongen**

### CODE REVIEW

**Comment by emmericp** [comment]
can you please clean up the history by squashing this together into a single commit?

**Comment by NetronomeMoongen** [comment]
I tried to pull as many of the commits together into a single commit by
squashing them. I will try in future to only commit once / as few times as
possible.

Sorry for the inconvenience and history clutter.

**Comment by emmericp** [comment]
now it's 11 commits instead of 9 ;)

use push --force to get rid of the old ones

**Comment by NetronomeMoongen** [comment]
Hopefully the number of commits should be less now :)

Once again sorry for the inconvenience. I'm still reltively new to git.

**Comment by emmericp** [comment]
i squashed it on my end during the merge since I'm about to do a conflicting commit (update libmoon as well).

this means that your branch now diverges due to the squashes vs. non-squashed merged commit, but you should be able to merge origin/master back into your repository

**Comment by NetronomeMoongen** [comment]
Thanks. Will re-merge with the MoonGen master branch and update the
packetgen.lua script and related files accordingly.

**Comment by NetronomeMoongen** [comment]
I noticed that the examples in the base directory of the repo use the
startTask method in the moongen module, while the examples in the libmoon
directory use the startTask method / function from the libmoon lua module.

Is the plan to move to using the moongen module, or the libmoon module ?

Also, will the examples be moved to the libmoon directory, or will the
examples be kept separate ? (libmoon examples and non-libmoon examples)

I'm just trying to understand which direction MoonGen is heading before
updating the packetgen lua script :)

**Comment by emmericp** [comment]
MoonGen should only contain packet-generator specific parts, so the location of your script is fine.

The libmoon vs. moongen module situation is somewhat confusing. Basically,
```require "moongen"``` and ```require "libmoon"``` do the same thing.
Well, the moongen module actually extends the libmoon module and adds wrappers for functions that were renamed (with a warning to use the new one).

I suggest to only use the moongen module for a moongen packet generator, but using libmoon is also fine.


> Am 16.11.2016 um 14:54 schrieb Netronome-moongen <notifications@github.com>:
> 
> I noticed that the examples in the base directory of the repo use the
> startTask method in the moongen module, while the examples in the libmoon
> directory use the startTask method / function from the libmoon lua module.
> 
> Is the plan to move to using the moongen module, or the libmoon module ?
> 
> Also, will the examples be moved to the libmoon directory, or will the
> examples be kept separate ? (libmoon examples and non-libmoon examples)
> 
> I'm just trying to understand which direction MoonGen is heading before
> updating the packetgen lua script :)
> 
> On Wed, Nov 16, 2016 at 3:43 PM, Philip van der Westhuizen <

**Comment by NetronomeMoongen** [comment]
Thank you.

I will update the packet generator script to use moongen instead of libmoon
to be mre in-line with your structure / architecture.

**Pull request merged**
