### PR TITLE
Routing modules + Routing example + various changes to the MoonGen core

### PR DESCRIPTION
**Pull request by schoenb**

### CODE REVIEW

**Comment by emmericp** [comment]
/home/paul/MoonGen/src/device.c:9:20: fatal error: device.h: No such file or directory
 #include "device.h"
                    ^
compilation terminated.

**Comment by emmericp** [comment]
/home/paul/MoonGen/src/5tuple.c:85:24: fatal error: ixgbe_logs.h: No such file or directory
 #include "ixgbe_logs.h"
                        ^
compilation terminated.

**Comment by emmericp** [comment]
/home/paul/MoonGen/src/5tuple.c:85:29: fatal error: ixgbe/ixgbe_api.h: No such file or directory
 #include "ixgbe/ixgbe_api.h"
                             ^
compilation terminated.

**Comment by emmericp** [comment]
maybe it's easier to patch DPDK to fix the 5tuple filter stuff on X540 NICs instead of copying it?

**Comment by schoenb** [comment]
now it is working. I forgot to commit the new CMakeLists.txt

**Comment by emmericp** [comment]
Could not run main script: lua/include/device.lua:8: module 'error' not found:

shouldnt this be part of dpdk or dpdkc?

**Comment by schoenb** [comment]
-> error.lua in git...
this is embarrassing :(

**Comment by schoenb** [comment]
I will move the error function to dpdk.lua later. I plan on extending this a bit first.

**Pull request merged**
