### PR TITLE
Add L2 PTP packet format and support for PTP sequenceId

### PR DESCRIPTION
**Pull request by duk3luk3**
It's all in packet.lua idk.

### CODE REVIEW

**Comment by duk3luk3** [comment]
is all good now

**Comment by duk3luk3** [comment]
There I fixed it.

**Comment by scholzd** [comment]
struct __attribute__((__packed__)) ptp_header {
...
+		uint8_t	reserved;
...
+		uint32_t	reserved;
Does this work (same name)?

Some setter methods are missing byteorder changes (e.g. ptpNodePort)

**Comment by duk3luk3** [comment]
uint8_t reserved; ...
    uint32_t reserved; Does this work (same name)?
Fixed.

> Some setter methods are missing byteorder changes (e.g. ptpNodePort)

Fixed ptpNodePort and sequenceId, I will need to check if correction needs to be byteswapped and then make a hton64 function.

**Pull request merged**
